# Frontend (HTTP)
server {
    listen 80;
    listen [::]:80;
    server_name internlog.cc.cd localhost;

    location / {
        resolver 127.0.0.11 valid=30s;
        set $upstream_frontend http://frontend:80;
        proxy_pass $upstream_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Backend BE (HTTP)
server {
    listen 80;
    listen [::]:80;
    server_name api.internlog.cc.cd;

    location / {
        resolver 127.0.0.11 valid=30s;
        set $upstream_backend http://backend:80;
        proxy_pass $upstream_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
